#ifndef BSP_BOARD_H
#define BSP_BOARD_H

#include "stm32l4xx_hal.h"

#define BSP_LED_PWM_GPIO_PORT GPIOA
#define BSP_LED_PWM_GPIO_PIN GPIO_PIN_5
#define BSP_LED_PWM_GPIO_AF GPIO_AF1_TIM2
#define BSP_LED_PWM_TIM TIM2
#define BSP_LED_PWM_TIM_CHANNEL TIM_CHANNEL_1

#define BSP_CLI_UART USART2
#define BSP_CLI_UART_BAUDRATE 115200U
#define BSP_CLI_UART_GPIO_PORT GPIOA
#define BSP_CLI_UART_TX_PIN GPIO_PIN_2
#define BSP_CLI_UART_RX_PIN GPIO_PIN_3
#define BSP_CLI_UART_GPIO_AF GPIO_AF7_USART2

#endif /* BSP_BOARD_H */
